name: AI-Powered Code Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-code-review:
    # Use a GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      - name: Send PR details to Code Review API
        id: send_review
        env:
          API_URL: http://44.201.184.34:30798/review
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          JSON_PAYLOAD="{\"repository\":\"$REPO\",\"pull_request_number\":$PR_NUMBER,\"diff\":\"\"}"
          curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD"
